# Logging
logging:
  level:
    root: INFO

#MYSQL CONFIGURATION
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventariopc
    username: root
    password: Fahaadahmed1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect